name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        python-version
    steps:
    - uses: actions/checkout@v3
    - name: All test
      run: bash -xv ./test.bash
